'use client'

import Link from 'next/link'
import { motion } from 'framer-motion'
import type { ReactNode } from 'react'
import { expertise, methodSteps, offers, projects, type Project } from '../lib/content'
import { ArrowIcon, ArrowLink, MaskImage, Reveal, SectionHeading, ease } from './motion-primitives'
import { Accordion, ClientMarquee, ContactBand, ProjectGrid, Testimonials } from './sections'
import { ContactForm } from './contact-form'

function PageIntro({ eyebrow, children, description }: { eyebrow: string; children: ReactNode; description?: string }) {
  return <section className="page-intro content-width"><motion.p className="eyebrow" initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ duration: 0.6 }}>{eyebrow}</motion.p><div className="page-title-mask"><motion.h1 initial={{ y: 70, opacity: 0 }} animate={{ y: 0, opacity: 1 }} transition={{ duration: 1.1, ease }}>{children}</motion.h1></div>{description && <motion.p className="page-intro-description" initial={{ opacity: 0, y: 15 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.8, delay: 0.2 }}>{description}</motion.p>}</section>
}

function OffersPage() {
  return <><PageIntro eyebrow="Nos offres" description="Un accompagnement pensé pour faire évoluer votre marque, en image comme en performance.">Pas d’offre par défaut.<br />Une offre pour <em>votre besoin.</em></PageIntro><div className="offer-details content-width">{offers.map((offer, index) => <section className={`offer-detail ${index % 2 ? 'offer-detail--reverse' : ''}`} id={offer.id} key={offer.id}><MaskImage src={offer.image} alt={offer.name} className="offer-detail-image" /><Reveal className="offer-detail-copy"><p className="eyebrow">0{index + 1} — {offer.label}</p><h2>{offer.name}</h2><h3>{offer.description}</h3><p>{offer.intro}</p><ul>{offer.features.map(feature => <li key={feature}><span aria-hidden="true">❊</span>{feature}</li>)}</ul><ArrowLink href={`/v3/contact?offre=${encodeURIComponent(offer.name)}`} filled>Parlons de votre projet</ArrowLink><p className="offer-detail-note">Chaque projet est pensé sur mesure. Le vôtre aussi.</p></Reveal></section>)}</div><section className="faq-section content-width"><SectionHeading eyebrow="Quelques réponses">Vous vous posez<br /><em>peut-être la question.</em></SectionHeading><Accordion items={[{ title: 'Quelle offre est faite pour ma marque ?', text: 'Lors de notre premier échange, nous prenons le temps de comprendre votre situation, votre ambition et vos priorités. Nous vous orientons vers l’accompagnement le plus pertinent, sans offre imposée ni service superflu.' }, { title: 'Puis-je faire évoluer mon site ensuite ?', text: 'Oui. Nous concevons des sites évolutifs et vous accompagnons dans leur prise en main. Vous restez autonome pour les mises à jour du quotidien, et nous restons disponibles pour les évolutions plus importantes.' }, { title: 'Comment se déroule la collaboration ?', text: 'Notre collaboration suit quatre temps : immersion, direction, création et déploiement. Vous êtes associé à chaque étape, avec des échanges réguliers et des points de validation clairs.' }, { title: 'Quels sont les délais de réalisation ?', text: 'Selon l’accompagnement, comptez entre deux et huit semaines après le cadrage. Nous vous donnons un calendrier précis dès le lancement, avec des jalons que vous validez tout au long du projet.' }]} /></section><ContactBand /></>
}

function ProjetsPage() {
  return <><PageIntro eyebrow="Nos réalisations" description="Des rencontres, des idées, et l’envie de faire la différence.">Découvrez les projets<br />sur lesquels nous avons <em>travaillé.</em></PageIntro><section className="portfolio-page content-width"><ProjectGrid filterable /></section><ContactBand /></>
}

function AboutPage() {
  return <><PageIntro eyebrow="À propos" description="Un regard créatif. Une vision stratégique. Et beaucoup d’engagement.">Un studio indépendant.<br />Une ambition : <em>la vôtre.</em></PageIntro><section className="about-story content-width"><MaskImage src="/v3/images/studio-editorial.webp" alt="L’univers sensible et créatif de L’AGENCE Design Studio" className="about-story-image" /><Reveal className="about-story-copy"><p className="eyebrow">L’AGENCE Design Studio</p><h2>De la sensibilité.<br />De l’exigence.<br /><em>Du sens.</em></h2><p>Fondé par Angélique Damour, L’AGENCE Design Studio accompagne les marques qui souhaitent affirmer leur singularité et faire de leur présence digitale un véritable atout.</p><p>Nous croyons qu’une image juste ne se contente pas d’être belle. Elle raconte, elle attire et elle inspire confiance. Elle donne envie de vous choisir.</p><p>Notre approche croise stratégie, identité visuelle et conception web pour créer des expériences cohérentes, sensibles et performantes.</p><ArrowLink href="/v3/manifeste">Lire notre manifeste</ArrowLink></Reveal></section><section className="studio-stats content-width"><Reveal><span>170<sup>+</sup></span><p>Projets & collaborations</p></Reveal><Reveal delay={0.1}><span>2019</span><p>Le début de l’histoire</p></Reveal><Reveal delay={0.2}><span>100<sup>%</sup></span><p>D’engagement, à chaque projet</p></Reveal></section><section className="about-clients"><SectionHeading eyebrow="La confiance se construit">De jeunes entreprises<br />à des <em>maisons reconnues.</em></SectionHeading><ClientMarquee /></section><Testimonials /><ContactBand /></>
}

function ContactPage() {
  return <><PageIntro eyebrow="Parlons de votre projet" description="Vous avez une idée, une ambition, un nouveau chapitre à écrire ? Nous avons hâte de vous rencontrer.">Et si on créait<br />quelque chose de <em>singulier ?</em></PageIntro><section className="contact-layout content-width"><Reveal className="contact-sidebar"><p className="eyebrow">La première rencontre</p><h2>Tout commence<br />par <em>un échange.</em></h2><p>Parlez-nous de votre marque et de ce que vous imaginez pour la suite. Nous prendrons le temps de comprendre votre projet.</p><div className="contact-direct"><a href="mailto:contact@lagencedesignstudio.com">contact@lagencedesignstudio.com <ArrowIcon diagonal /></a><a href="tel:+33777703041">+33 (0)7 77 70 30 41 <ArrowIcon diagonal /></a></div><div className="contact-availability"><span /><p>À votre écoute<br /><small>Réponse sous 24h — sans engagement</small></p></div><MaskImage src="/v3/images/editorial-skin.webp" alt="Le sens du détail, au cœur de notre approche" className="contact-sidebar-image" parallax={false} /></Reveal><ContactForm /></section></>
}

function MethodPage() {
  return <><PageIntro eyebrow="Notre méthode" description="Créer le désir. Élever la perception. Positionner votre marque.">Le <em>Brand Desire</em><br />System<sup>™</sup></PageIntro><Reveal className="method-page-lead content-width"><p>Le design n’est pas une simple question d’esthétique. C’est un outil pour révéler votre valeur, affirmer votre positionnement et donner envie de vous choisir.</p><p>Notre méthode relie stratégie et création, du premier échange jusqu’au lancement.</p></Reveal><section className="method-steps content-width">{methodSteps.map((step, index) => <Reveal className="method-step" key={step.title}><span className="step-number">0{index + 1}</span><div><p className="eyebrow">Brand Desire System™</p><h2>{step.title}</h2><p>{step.text}</p></div><span className="step-flower" aria-hidden="true">❊</span></Reveal>)}</section><ContactBand /></>
}

function ExpertisePage() {
  return <><PageIntro eyebrow="Nos expertises" description="Chaque service s’inscrit dans une réflexion globale.">Stratégie, design et digital.<br />Pour construire des marques <em>plus fortes.</em></PageIntro><section className="expertise-content content-width"><div className="expertise-image"><MaskImage src="/v3/images/editorial-beauty.webp" alt="Une direction artistique au service de votre singularité" className="expertise-portrait" /><p className="eyebrow">Une vision d’ensemble.<br />Le sens du détail.</p></div><Accordion items={expertise} /></section><ContactBand /></>
}

function SolutionsPage() {
  const sectors = [{ title: 'Beauté', image: 'editorial-beauty', text: 'Des univers de marque qui révèlent votre expertise et donnent envie de découvrir vos produits.' }, { title: 'Bien-être', image: 'editorial-skin', text: 'Des expériences sensibles qui traduisent votre approche et inspirent une confiance durable.' }, { title: 'Food', image: 'project-nouvelle-garde', text: 'Des identités généreuses et des expériences digitales qui donnent le goût de vous rencontrer.' }, { title: 'Lifestyle', image: 'project-atelier', text: 'Des marques singulières qui incarnent un art de vivre et créent une connexion avec leur communauté.' }]
  return <><PageIntro eyebrow="Nos solutions" description="Une approche sur mesure, des enjeux que nous comprenons.">Votre univers.<br />Notre regard. <em>La rencontre.</em></PageIntro><section className="sector-grid content-width">{sectors.map((sector, index) => <Reveal className="sector-card" key={sector.title}><MaskImage src={`/v3/images/${sector.image}.webp`} alt={`Notre expertise ${sector.title.toLowerCase()}`} className="sector-image" /><div className="sector-copy"><span className="eyebrow">0{index + 1}</span><h2>{sector.title}</h2><p>{sector.text}</p><ArrowLink href="/v3/contact">Imaginons votre projet</ArrowLink></div></Reveal>)}</section><ContactBand /></>
}

function ManifestoPage() {
  const beliefs = [{ title: 'Le beau doit avoir du sens.', text: 'Nous ne créons pas pour suivre une tendance. Nous créons pour exprimer ce qui vous rend unique, avec justesse et intention.' }, { title: 'La différence se cultive.', text: 'Une marque forte n’essaie pas de ressembler aux autres. Elle affirme une vision, un point de vue, une façon de faire qui lui appartient.' }, { title: 'Le détail n’est jamais un détail.', text: 'Du choix d’une typographie à la fluidité d’un parcours, chaque décision contribue à l’expérience et à la perception de votre marque.' }, { title: 'Nous avançons ensemble.', text: 'La confiance, l’écoute et le dialogue sont les fondations d’un beau projet. Votre ambition devient la nôtre, du premier échange au dernier ajustement.' }]
  return <><PageIntro eyebrow="Notre manifeste">Le beau ne suffit pas.<br />Il faut <em>du sens.</em></PageIntro><section className="manifesto content-width">{beliefs.map((belief, i) => <Reveal className="manifesto-belief" key={belief.title}><span>( 0{i + 1} )</span><div><h2>{belief.title}</h2><p>{belief.text}</p></div></Reveal>)}</section><ContactBand /></>
}

function LegalPage({ slug }: { slug: string }) {
  const title = slug === 'mentions-legales' ? 'Mentions légales' : slug === 'cgv' ? 'Conditions générales' : 'Politique de confidentialité'
  return <><PageIntro eyebrow="Informations">{title}</PageIntro><article className="legal-content content-width"><h2>À propos de cette interface</h2><p>Cette application est une recréation technique du site L’AGENCE Design Studio, réalisée à des fins de démonstration. Les noms, marques et visuels présentés appartiennent à leurs titulaires respectifs. Cette interface n’est pas le site officiel de l’agence.</p><h2>Vos données personnelles</h2><p>Les informations transmises par le formulaire de contact sont enregistrées dans la base de données de cette application. Elles ne sont pas envoyées à l’agence d’origine. Les champs obligatoires permettent de comprendre la nature de votre demande.</p><p>Ne transmettez pas d’informations sensibles dans le formulaire. Votre consentement est demandé avant tout enregistrement. Vous pouvez demander l’accès, la correction ou la suppression d’une demande en indiquant sa référence dans un nouveau message via le formulaire.</p><h2>Cookies et préférences</h2><p>Cette version ne charge pas de suivi publicitaire ni de service de mesure d’audience tiers. Vos préférences de consentement sont conservées localement dans votre navigateur. Vous pouvez les modifier à tout moment avec le bouton « Gérer le consentement ».</p><h2>Propriété intellectuelle</h2><p>Les photographies, marques et contenus de référence sont présentés pour reproduire l’expérience visuelle demandée. Ils ne peuvent être réutilisés indépendamment sans l’autorisation de leurs propriétaires.</p><h2>Demandes et prestations</h2><p>Le formulaire n’engage à aucune prestation ni aucun paiement. Aucun contrat n’est conclu depuis cette démonstration. Toute prestation réelle nécessite un accord distinct avec son prestataire.</p><ArrowLink href="/v3/contact">Accéder au formulaire</ArrowLink></article></>
}

export function StandardPageView({ slug }: { slug: string }) {
  let content: ReactNode
  switch (slug) {
    case 'offres': content = <OffersPage />; break
    case 'projets': content = <ProjetsPage />; break
    case 'a-propos': content = <AboutPage />; break
    case 'contact': content = <ContactPage />; break
    case 'methode': content = <MethodPage />; break
    case 'expertises': content = <ExpertisePage />; break
    case 'solutions': content = <SolutionsPage />; break
    case 'manifeste': content = <ManifestoPage />; break
    default: content = <LegalPage slug={slug} />
  }
  return <main id="v3-main-content" className={`inner-page page-${slug}`}>{content}</main>
}

export function ProjectDetailView({ project }: { project: Project }) {
  const next = projects[(projects.findIndex(item => item.slug === project.slug) + 1) % projects.length]
  return <main id="v3-main-content" className="project-detail-page"><section className="project-detail-intro content-width"><Reveal><Link className="project-back text-link" href="/v3/projets">← Toutes les réalisations</Link><p className="eyebrow">{project.category} — {project.year}</p><h1>{project.name}</h1><p className="project-detail-tagline">{project.description}</p></Reveal><Reveal className="project-service-list" delay={0.15}><p className="eyebrow">Notre accompagnement</p>{project.services.map(service => <span key={service}>{service}</span>)}</Reveal></section><div className="project-detail-hero" style={{ backgroundColor: project.color }}><MaskImage src={project.image} alt={`${project.name} — création sur mesure par L’AGENCE Design Studio`} className="project-detail-photo" priority /></div><section className="project-story content-width"><Reveal><p className="eyebrow">Le projet</p><h2>Révéler l’essentiel.<br /><em>Faire la différence.</em></h2></Reveal><Reveal><p>{project.detail}</p><p>Un projet pensé dans sa globalité, avec le même niveau d’exigence pour l’image, l’expérience et la performance.</p><ArrowLink href="/v3/contact">Un projet similaire ? Parlons-en</ArrowLink></Reveal></section><section className="next-project"><Link href={`/v3/projet/${next.slug}`}><div><p className="eyebrow">La suite des belles histoires</p><h2>{next.name}</h2></div><ArrowIcon diagonal /><img src={next.image} alt="" width="260" height="180" loading="lazy" /></Link></section></main>
}
